language: cpp
os: linux

# require the branch name to be master
if: branch = master

before_install:
    - eval "${MATRIX_EVAL}"
    
script:
- cd Assignments
- mkdir build-travis
- cd build-travis
- cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX
- make -j3

matrix:
  include:
    - addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
          packages:
          - clang-6.0
          - libstdc++-8-dev
      env:
      - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-7
          packages:
          - clang-7
          - libstdc++-8-dev
      env:
      - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

    - addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-8
      env:
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
